### PR TITLE
fix: downgrade source-map

### PR DESCRIPTION
**Pull request by DanielRuf**
Currently in the lockfile there is a different / older version of `source-map` so it works on Node.js 6 on CI.

But after it is published only the package.json is used and so source-map 0.7 is used which required `node > 8` and breaks setups which run on Node.js 6 LTS.

You can easily check this by using npm 3 which did not yet support the lockfile and just supported shrinkwrap.

https://travis-ci.org/anandthakker/doiuse/jobs/434179068#L452

### CODE REVIEW

**Comment by ncoden** [comment]
Poke @pkuczynski

**Comment by DanielRuf** [comment]
Bump.

**Comment by pkuczynski** [comment]
I am wondering if it makes sense to support node 6?

**Comment by DanielRuf** [comment]
Closing as there are conflicts now and things may have changed since then.

**Comment by DanielRuf** [comment]
> I am wondering if it makes sense to support node 6?

Not anymore but some projects still use and support Node 6.

**Pull request closed without merging**
