### PR TITLE
Bump browserlist version

### PR DESCRIPTION
**Pull request by Gurylev**
#37

### CODE REVIEW

**Comment by anandthakker** [comment]
:+1:

**Comment by Gurylev** [comment]
please npm publish

**Comment by anandthakker** [comment]
@Gurylev sure, although I'm not sure this will actually resolve #37, since we're [calling browserslist manually](https://github.com/anandthakker/doiuse/blob/master/src/browsers.js#L7)

**Comment by anandthakker** [comment]
Published in 2.2.2

**Pull request merged**
