### PR TITLE
fix: Remove security warning

### PR DESCRIPTION
**Pull request by JackHowa**
see issue #119 ... updates to security warning minimum

### CODE REVIEW

**Comment by JackHowa** [comment]
@anandthakker do you have time to review the pr?

**Comment by JackHowa** [comment]
@pkuczynski @ai do you have time to review the dependency fix?

**Comment by ai** [comment]
@JackHowa sorry, it is not my project.

Try to reach @pkuczynski by email.

**Comment by JackHowa** [comment]
@ai ok thanks, sorry to bother ya'

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
I will release a new version tomorrow afternoon, if you don't mind?

**Comment by JackHowa** [comment]
thanks @pkuczynski ! really appreciate it

**Comment by JackHowa** [comment]
Let me know @pkuczynski if you have time to publish this?

**Comment by pkuczynski** [comment]
I tried to release but found out that build is failing. Didnt had time to check why. If you have some time, maybe you can have a look?

**Comment by jimmybrawn** [comment]
https://github.com/anandthakker/doiuse/pull/121/files Update on CLI test

**Pull request merged**
