### PR TITLE
Remove `css-scroll-timeline`

### PR DESCRIPTION
**Pull request by AlexWayfer**
It has been deleted in `caniuse` 1.0.30001655

### CODE REVIEW

**Review by tomoayan — APPROVED** [review]

**Comment by dargmuesli** [comment]
@clshortfuse may I request a short review from you on this breaking issue? :heart:

**Comment by alSergey** [comment]
Hi, is there any progress on this merge request? Now I have to write an override on the caniuse-lite library, which is very inconvenient. I would like to have a full solution to the problem.

**Comment by clshortfuse** [comment]
Thanks for the PR. Unfortunately modifications to the `package-lock.json` aren't things that should be done over PR for security reasons. So I had to pull the repo and do it manually. Then I got into a whole ordeal trying to get the codebase testing to work with node v20.

You don't actually have to remove the feature. We should just account for the discrepancy between the two. If not, we'd be having to patch every single time something gets removed from caniuse.  I added a recent commit that should resolve that. I'll try to fix whatever's going on with npm v20 and push a npm update.

**Comment by dargmuesli** [comment]
Thank you very much for your work @clshortfuse! :green_heart:

**Comment by clshortfuse** [comment]
@AlexWayfer can you modify the PR to just remove the feature without the package related changes?

**Comment by AlexWayfer** [comment]
> @AlexWayfer can you modify the PR to just remove the feature without the package related changes?

I'm still not sure how do you catch this, but excluding package changes — not a problem, I can do this at this weekend.

**Comment by dargmuesli** [comment]
Hmm, I think something broke with v6.0.3:

image

Seems like this `.some` here works differently now: https://github.com/anandthakker/doiuse/commit/5199d866ed88d86b2c833078ee62264bb9604226

**Comment by AlexWayfer** [comment]
@clshortfuse done. Is it okay now?

**Comment by Opty1712** [comment]
I have problems too, take a look here
https://github.com/browserslist/caniuse-lite/issues/133

Please remove this feature and make a release

**Review by Opty1712 — APPROVED** [review]

**Comment by clshortfuse** [comment]
Pushed v6.0.5 to npm

**Pull request merged**
