### PR TITLE
Fixed possible regular expression catastrophic backtracking

### LINKED ISSUE #95: Poor performance of a particular example on ie 6
Hi I get very poor performance for elements with `:focus:hover` when checking them against `ie 6`.
Example:
```zsh
$ time doiuse --browsers "ie 6" example.css
example.css:1:1: CSS 2.1 selectors not supported by: IE (6) (css-sel2)
doiuse --browsers "ie 6" example.css  59,04s user 0,06s system 100% cpu 59,014 total
```
where `example.css` is:
```css
.imagelightbox-arrow:focus:hover {
}
```

I've found that changing the name of the class sometimes resolves the issue, as does removing either the `hover` or the `focus`. From what I can tell, the content of the class has no effect.

I am using version 4.2.0

### PR DESCRIPTION
**Pull request by marekdedic**
Fixes #95

### CODE REVIEW

**Comment by GenaBitu** [comment]
I don't think the failing CI has anything to do with the PR - let me know if it does.

**Comment by marekdedic** [comment]
Hey, any progress on this? This isa blocking issue for me...

Thanks a lot,
Marek

**Comment by pkuczynski** [comment]
@marekdedic, apologies for the late reply. Could you provide some tests and changelog entry for this?

**Comment by marekdedic** [comment]
Hi, thanks for the reply anyway :slightly_smiling_face: 

I've added a changelog entry, however, I'm a bit stuck with the tests, see #126.

**Comment by pkuczynski** [comment]
@marekdedic I had a look at the example you provided and after adding `?` as you suggest, I am only getting a match on `.`:

https://regex101.com/r/MlbAhW/1 vs https://regex101.com/r/MlbAhW/2

I don't think this is correct?

**Comment by marekdedic** [comment]
Hmm, it's not correct. I don't really know how to fix it though, as I am not really sure what the `mathOutsideOfBrackets` function does...

**Comment by pkuczynski** [comment]
To be honest, I don't know either. I have not written this package and I am only maintaining it. Approving PR and releasing the new versions. The only person who knows is @anandthakker, but he is not responsive :(

**Review by pkuczynski — CHANGES_REQUESTED** [review]
Does not seem to work...

**Comment by marekdedic** [comment]
Hi,
I looked over it once more and it seems to me that the function `matchOutsideOfBrackets(X)` checks whether there is the character`X` somewhere **not** inside `[]` or `()`. So the match on `.` would actually be correct. And expanding the regex constructed by `mathcOutsideOfBrackets`, the non-greedy approach doesn't change the meaning.

So I do actually think this PR is correct, however there is one more thing... We can actually undo #88 with this change and simplify it!

**Comment by marekdedic** [comment]
(and undoing #88 would allow for testing for catastrophic regexes...)

**Comment by marekdedic** [comment]
Hi, the PR is now working and with tests for unsafe regexes (not limited to the one in #95)

**Comment by marekdedic** [comment]
Hmm, so the tests wouldn't catch #95. I've tried switching safe-regex for vuln-regex-detector but that seems to be abandoned... So at least an imperfect test...

**Review by pkuczynski — APPROVED** [review]
As I said before, I am not able to fairly judge the changes. If you confident this is correct, I am fine with merging it and releasing as next version.

**Comment by pkuczynski** [comment]
And thank you for putting effort into this! :)

**Comment by marekdedic** [comment]
Hold your horses. I think I've found some more performance issues with this function. Going to go for a different solution to solve it once and for all.

**Comment by marekdedic** [comment]
Hi, I've reworked it to not use such a horrendous regex but a simpler function instead. Unit tests pass, tried it on 2 of my projects, same output, no performance issues. I think you can merge this now.

**Comment by pkuczynski** [comment]
Let's give it a try and release it as next major version :)

**Pull request merged**
