### PR TITLE
Update test for failing build

### PR DESCRIPTION
**Pull request by jimmybrawn**
This is blocking the yargs update release

### CODE REVIEW

**Review by pkuczynski — APPROVED** [review]

**Comment by pkuczynski** [comment]
The build still fails. Can you have a look?

**Comment by jimmybrawn** [comment]
> The build still fails. Can you have a look?

If I fix node:stable, then node:6 fails. If I fix node:6 then stable fails. Do we even support node 6 still?

**Comment by jimmybrawn** [comment]
Fixed the issue accordingly, please review file to see if solution could bring potential side effects?

**Comment by jimmybrawn** [comment]
@pkuczynski can we release it now?

**Comment by pkuczynski** [comment]
Thanks for all the work you put into this! Merging and releasing now...

**Pull request merged**
